#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - name: savi
    ssh-authorized-keys:
      - ${ssh_pubkey}
    gecos: deployment and admin user
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    #TODO: remove password for actual use
    passwd: $6$i/VkKOsRGFpx06Va$VWsZBwLKhorKd0ugUosONVH.ELN0b.qpwTBNK/6NfYp7rGPpyU/p9pqkgz0Vm7N6/iqO6YctqAq1GSlrZLlXy/
    lock_passwd: false
timezone: US/Eastern
package_update: true
#package_upgrade: true #TODO: uncomment for actual use
runcmd:
  - "git clone https://github.com/RIT-Election-Security/SAVI-deployment"
  # and then we do a bunch of sed replacements to get everything right
  - "sed -i -e 's/<registrar-ip>/${registrar_ip}/' /home/savi/SAVI-deployment/inventory.yaml"
  - "sed -i -e 's/<ballotbox-ip>/${ballotbox_ip}/' /home/savi/SAVI-deployment/inventory.yaml"
  - "sed -i -e 's/<ballotserver-ip>/${ballotserver_ip}/' /home/savi/SAVI-deployment/inventory.yaml"
  - "sed -i -e 's/<resultserver-ip>/${resultserver_ip}/' /home/savi/SAVI-deployment/inventory.yaml"
  - "sed -i -e 's/<admin-user>/savi/' /home/savi/SAVI-deployment/group_vars/all.yaml"
  - "sed -i -e 's/<registrar-address>/${registrar_ip}/' /home/savi/SAVI-deployment/group_vars/all.yaml"
  - "sed -i -e 's/<ballot-box-address>/${ballotbox_ip}/' /home/savi/SAVI-deployment/group_vars/all.yaml"
  - "sed -i -e 's/<ballot-server-address>/${ballotserver_ip}/' /home/savi/SAVI-deployment/group_vars/all.yaml"
  - "sed -i -e 's/<result-server-address>/${resultserver_ip}/' /home/savi/SAVI-deployment/group_vars/all.yaml"
