#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - name: savi
    ssh-authorized-keys:
      - ${ssh_pubkey}
    gecos: deployment and admin user
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    lock_passwd: false
timezone: US/Eastern
apt_sources:
  - source: "ppa:ansible/ansible"
package_update: true
#package_upgrade: true #TODO: uncomment for actual use on older images
packages:
  - git
  - software-properties-common
  - ansible
  - python-pip
  - unzip
  - python-apt