#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - name: savi
    ssh-authorized-keys:
      - ${ssh_pubkey}
    gecos: deployment and admin user
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    #TODO: remove password for actual use
    passwd: $6$i/VkKOsRGFpx06Va$VWsZBwLKhorKd0ugUosONVH.ELN0b.qpwTBNK/6NfYp7rGPpyU/p9pqkgz0Vm7N6/iqO6YctqAq1GSlrZLlXy/
    lock_passwd: false
timezone: US/Eastern
package_update: true
#package_upgrade: true #TODO: uncomment for actual use
packages:
  - git
  - python-pip
#TODO: use python3 to deal with warnings; probably needs a newer python
runcmd:
  - pip install ansible
