#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - name: savi
    ssh-authorized-keys:
      - ${ssh_pubkey}
    gecos: deployment and admin user
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    lock_passwd: true
timezone: US/Eastern
package_update: true
#package_upgrade: true #TODO: re-enable this in prod use
packages:
  - python-pip
runcmd:
  - "pip install --upgrade pip"