#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
users:
  - name: savi
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINbIPcBCcjTsH1PcqxG9dGCXP/d8xlctDdjzw6ed/uIu #TODO: replace key
    gecos: whiteteam user
    groups: [adm, sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    lock_passwd: true
timezone: US/Eastern
package_update: true
package_upgrade: true
